### ISSUE TITLE
arming / disarming motion alarm

### ISSUE THREAD

**Issue by stephanhaas** [edwinvdpol/com.foscam#4] opened 2019-03-01 21:03 UTC
No idea if it's possible, but I would like the option of arming/disarming the motion alarm. This would make it possible to arm/disarm dependent of the presence of the family

**Comment by edwinvdpol** [comment] 2019-03-01 22:03
Yes, this is certainly possible.
Added to the todo list, and will be in the next release. 👍

**Comment by stephanhaas** [comment] 2019-03-02 06:25
Great, looking forward to it.

**Comment by edwinvdpol** [comment] 2019-03-08 10:05
Version 1.2.0 is released and supports motion detection settings / flowcards.

**Comment by stephanhaas** [comment] 2019-03-08 10:28
Saw the message and of course tested it right away. Unfortunately I get an
error message: "Cannot set property 'isEnable' of null. Camera is R2.

Op vr 8 mrt. 2019 om 11:05 schreef E. van de Pol <notifications@github.com>:

**Comment by edwinvdpol** [comment] 2019-03-08 10:33
Can you restart the app and try again?
If that does not work, can you please send a piece of the log / diagnostic report?

**Comment by stephanhaas** [comment] 2019-03-08 11:09
Restart didn't. Help. 

cca1217b-2035-434f-98b9-9fc1d3585a2d should be the code for the diagnostics report.


Met vriendelijke groet,
Stephan Haas

**Comment by edwinvdpol** [comment] 2019-03-08 11:13
I see the report. Can you do something for me?

Can you reach the following URL's on your local network:
`http://[ip]:[port]/cgi-bin/CGIProxy.fcgi?cmd=getMotionDetectConfig&usr=[user]&pwd=[password]` and
`http://[ip]:[port]/cgi-bin/CGIProxy.fcgi?cmd=getPTZPresetPointList&usr=[user]&pwd=[password]` ?

**Comment by stephanhaas** [comment] 2019-03-08 11:31
and here are the results of the Dutch jury:


*http://[ip]:[port]/cgi-bin/CGIProxy.fcgi?cmd=getMotionDetectConfig&usr=[user]&pwd=[password]*

<CGI_Result>
    <result>-3</result>
</CGI_Result>

*http://[ip]:[port]/cgi-bin/CGIProxy.fcgi?cmd=getPTZPresetPointList&usr=[user]&pwd=[password]*

<CGI_Result>
    <result>-2</result>
</CGI_Result>


Op vr 8 mrt. 2019 om 12:13 schreef E. van de Pol <notifications@github.com>:

**Comment by edwinvdpol** [comment] 2019-03-08 11:39
Did you enter your username and password correctly?
The `<result>-2</result>` is a username or password error.

You are logging in with an admin account?
Do you have the latest [Foscam R2 firmware](http://www.foscam.eu/index.php/productattachments/index/view/u/R2_Firmware/) installed?

Please provide as much info as you can please.

**Comment by stephanhaas** [comment] 2019-03-08 12:24
Used the same username/password on both url's. They are OK, because these
work in the foscam app on my iphone. I use a non standard port .
Latest software. Same result.

Op vr 8 mrt. 2019 om 12:39 schreef E. van de Pol <notifications@github.com>:

**Comment by edwinvdpol** [comment] 2019-03-08 12:42
The Foscam App login is used to login on your Foscam account.
You need to enter the camera admin username and password.

**Comment by stephanhaas** [comment] 2019-03-08 12:45
I'm using a third party app (Foscam 2Pro) to get to the images of my camera
and that uses the admin account (although I changed the username). My
MyFoscam acount is indeed totally different.

BTW, I really appreciate your support!

Op vr 8 mrt. 2019 om 13:42 schreef E. van de Pol <notifications@github.com>:

**Comment by edwinvdpol** [comment] 2019-03-08 14:26
Somebody also has problems with the R2. Investigating!

**Comment by stephanhaas** [comment] 2019-03-08 16:21
Added a C2 as well. Same problem. I get a red triangle in the apparaten screen. Was not the case in the previous release.





Met vriendelijke groet,
Stephan Haas

**Comment by edwinvdpol** [comment] 2019-03-08 16:46
Yes, the problem occurs with the R2, R4 and C2 cameras I presume. Pinpointed the problem and working on a fix. Sorry for the inconvenience.

**Comment by stephanhaas** [comment] 2019-03-08 17:04
No worries 

Met vriendelijke groet,
Stephan Haas

**Comment by edwinvdpol** [comment] 2019-03-09 12:52
I have submitted version 1.2.1 in the app store which should fix the issue. Now wait for Athom to approve the app. Please let me know here if the issue is solved or not. Thanks!

**Comment by stephanhaas** [comment] 2019-03-12 08:30
Athom still in limbo.

**Comment by edwinvdpol** [comment] 2019-03-12 09:14
Like...?

**Comment by stephanhaas** [comment] 2019-03-12 10:08
As in: Athom has not yet approved the updated app.

Op di 12 mrt. 2019 om 10:25 schreef E. van de Pol <notifications@github.com

**Comment by edwinvdpol** [comment] 2019-03-12 10:10
Published 👍

**Comment by stephanhaas** [comment] 2019-03-12 10:39
Working like a charm now. Thanks.

Met vriendelijke groet,
Stephan Haas

**Comment by edwinvdpol** [comment] 2019-03-12 10:44
@stephanhaas Appreciated! Thanks!

**Closed by edwinvdpol** 2019-03-12 10:44 UTC
Labels: enhancement
